export const UPDATE_SUCCESS_USER = 'UPDATE_SUCCESS_USER';

export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';

export const CHECK_AUTHENTIFICATION_SUCCESS = 'CHECK_AUTHENTIFICATION_SUCCESS';
export const CHECK_AUTHENTIFICATION_ERROR = 'CHECK_AUTHENTIFICATION_ERROR';

export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
